#!/bin/bash
# ============================================
# Elasticsearch Installation Script (Manual)
# ============================================

echo "============================================"
echo "Elasticsearch Installation Options"
echo "============================================"

echo ""
echo "OPTION 1: Using Docker (Recommended)"
echo "----------------------------------------"
echo "docker pull docker.elastic.co/elasticsearch/elasticsearch:8.11.0"
echo "docker run -d --name elasticsearch \\"
echo "  -p 9200:9200 -p 9300:9300 \\"
echo "  -e 'discovery.type=single-node' \\"
echo "  -e 'xpack.security.enabled=false' \\"
echo "  docker.elastic.co/elasticsearch/elasticsearch:8.11.0"

echo ""
echo "OPTION 2: Using Docker Compose (Full ELK)"
echo "----------------------------------------"
echo "cd elasticsearch-project"
echo "docker-compose up -d"

echo ""
echo "OPTION 3: Manual Installation (Ubuntu/Debian)"
echo "----------------------------------------"
echo "# Import GPG key"
echo "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"
echo ""
echo "# Add repository"
echo "echo 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main' | sudo tee /etc/apt/sources.list.d/elastic-8.x.list"
echo ""
echo "# Install"
echo "sudo apt update && sudo apt install elasticsearch"
echo ""
echo "# Start service"
echo "sudo systemctl enable elasticsearch"
echo "sudo systemctl start elasticsearch"

echo ""
echo "OPTION 4: Manual Installation (CentOS/RHEL)"
echo "----------------------------------------"
echo "# Import GPG key"
echo "sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch"
echo ""
echo "# Add repository"
echo "cat <<EOF | sudo tee /etc/yum.repos.d/elasticsearch.repo"
echo "[elasticsearch]"
echo "name=Elasticsearch repository for 8.x packages"
echo "baseurl=https://artifacts.elastic.co/packages/8.x/yum"
echo "gpgcheck=1"
echo "gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch"
echo "enabled=1"
echo "autorefresh=1"
echo "type=rpm-md"
echo "EOF"
echo ""
echo "# Install"
echo "sudo yum install elasticsearch"
echo ""
echo "# Start service"
echo "sudo systemctl enable elasticsearch"
echo "sudo systemctl start elasticsearch"

echo ""
echo "============================================"
echo "Verify Installation"
echo "============================================"
echo "curl -X GET 'http://localhost:9200/?pretty'"

echo ""
echo "============================================"
echo "Install Kibana"
echo "============================================"
echo "# Docker"
echo "docker run -d --name kibana -p 5601:5601 --link elasticsearch:elasticsearch docker.elastic.co/kibana/kibana:8.11.0"
echo ""
echo "# APT"
echo "sudo apt install kibana"
echo "sudo systemctl enable kibana && sudo systemctl start kibana"

echo ""
echo "============================================"
echo "Access Points"
echo "============================================"
echo "Elasticsearch: http://localhost:9200"
echo "Kibana:        http://localhost:5601"
echo "ES-Head:       http://localhost:9100"
